Repository jamesmawm/golang-user-microservice, pull requests merged in 2020-10, with the labels that each got.

#2 Initial commit with base go codes, and add Readme.
  README.md
  core/api.go
  main.go
  swagger.yml
Labels: Hacktoberfest, documentation, good first issue

#9 environment variable via .env file
  .env
  config.json
  config/app.go
  config/database.go
  main.go
Labels: Hacktoberfest

#10 Add crud ops
  core/api.go
  main.go
Labels: Hacktoberfest

#12 Fix main to use v1/config instead of golang-user-microservice/config
  config.json
  config/app.go
  main.go
Labels: Hacktoberfest

#13 Add docker support
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: Hacktoberfest

#14 Feature/update documentation
  README.md
Labels: Hacktoberfest

#15 Add sqlite support
  core/db_util.go
  main.go
Labels: Hacktoberfest, hacktoberfest-accepted

#18 add go mod
  Dockerfile
  README.md
  go.mod
  go.sum
  main.go
Labels: Hacktoberfest, hacktoberfest-accepted

#19 Add simple sqlite support based on gorm
  boundary/api.go
  control/user_service.go
  core/api.go
  data/database.go
  dto/user_dto.go
  go.mod
  go.sum
  main.go
  model/user.go
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Docker fixes.
  .dockerignore
  Dockerfile
Labels: Hacktoberfest, hacktoberfest-accepted

#22 prevents duplicate usernames #20
  boundary/api.go
  control/user_service.go
  swagger.yml
Labels: Hacktoberfest, hacktoberfest-accepted

#23 Add mysql support
  boundary/api.go
  config/app.go
  config/database.go
  data/database.go
  go.mod
  go.sum
  main.go
Labels: Hacktoberfest, hacktoberfest-accepted

#24 feat: simple unit test around default database
  .gitignore
  data/database_test.go
Labels: Hacktoberfest, hacktoberfest-accepted
